// NOME DO PROFESSOR: ME. ANDRÉ QUEIROZ
// NOME DO ALUNO: WILKER LISBOA
// NOME DO ARQUIVO: ALPHA
// TRABALHO: ATIVIDADE 01
// DESCRIÇÃO: HELLO WORD
#include <stdio.h>

int main(){
    printf("HELLO WORD!!");
    return 0;
}